# Project info
site_name: stash-docs
site_description: 'stash Documentation'
site_author: 'AnTiMatteIR'
site_url: https://antimatteir.github.io/stash-docs/

# Repository info
repo_name: 'AnTiMatteIR/stash-docs'
repo_url: 'https://github.com/AnTiMatteIR/stash-docs'

extra_css:
  - css/stash.css

# Theme config
theme:
  name: 'material'
  language: en
  font: false
  logo: img/icon.jpg
  features:
    - navigation.instant
    #- navigation.tabs
    - navigation.sections

plugins:
  - search
  - macros:
      include_dir: include

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: 🔗
  - pymdownx.details
  - pymdownx.superfences

nav:
    - Getting started: index.md
    - Development: development.md
    # WIP
    #- Getting started:
    #  - Initial setup: getting-started/setup.md
    - Installation:
      - Synology NAS: installation/synology_nas.md
      - UNRAID: installation/unraid.md
    - Customization:
      - CSS snippets: customization/css-snippets.md
      - Themes:
        - Overview: customization/themes/overview.md
        - Pulsar theme: customization/themes/theme-pulsar.md
        - Night theme: customization/themes/theme-night.md
        - Plex theme: customization/themes/theme-plex.md
      - Plugins & Scripts:
        - Plugins: customization/plugins-scripts/plugins.md
        - Scripts: customization/plugins-scripts/scripts.md
    - Advanced:
      - Comand line options: advanced/cli-options.md
      - Exclude files from stash: advanced/exclude-files.md
      - Reverse proxy: advanced/reverse-proxy.md
    - Database:
      - Backup & Restore: database/backup-restore.md
      - Import CSV: database/import-csv.md
      - Edit manually: database/edit-manually.md
    - Troubleshooting:
      - Video playback issues: troubleshooting/video-playback.md
    - API:
      - Reference: api/reference.md
      - JSON specification: api/json-specification.md
